services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src/main/resources:/app/src/main/resources:ro
    environment:
      - JAVA_OPTS=-Xmx3000m -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/heap.hprof
      - TMDB_API_KEY=${TMDB_API_KEY}
      - GRAPH_RESOURCE_DIR=/app/src/main/resources
      - GRAPH_CACHE_FILE=/app/graph-cache.bin.gz
    restart: "no"
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: deps
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
      PORT: 3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm ci && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - backend
