services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx2g -Xms512m
      - TMDB_API_KEY=${TMDB_API_KEY}
      - SPRING_PROFILES_ACTIVE=database
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GRAPH_RESOURCE_DIR=/app/src/main/resources
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped