services:
  backend:
    image: cjprice2/celebrity-backend:latest
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/app/data
    environment:
      - JAVA_OPTS=-Xmx2g -Xms512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/app/heap.hprof
      - TMDB_API_KEY=${TMDB_API_KEY}
      - GRAPH_RESOURCE_DIR=/app/src/main/resources
      - SPRING_PROFILES_ACTIVE=database
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/celebrity_graph.db
      - BFS_MAX_VISITED=3000000
      - BFS_MAX_QUEUE=1000000
      - SKIP_DATA_LOADING=false
      - SKIP_INDEX_ENSURE=false
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 9G
        reservations:
          memory: 2G

  frontend:
    image: cjprice2/celebrity-frontend:latest
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://backend:8080}
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  sqlite_data:

