name: celebrity-shortest-path-finder

services:
- name: backend
  source_dir: backend
  github:
    repo: cjprice2/CelebrityShortestPathFinder
    branch: main
    deploy_on_push: true
  build_command: mvn clean package -DskipTests
  run_command: java -Xmx1g -Xms256m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -Dserver.address=0.0.0.0 -Dserver.port=$PORT -jar target/*.jar
  environment_slug: java
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: TMDB_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: GRAPH_RESOURCE_DIR
    scope: RUN_TIME
    value: "/app/src/main/resources"
  - key: SPRING_PROFILES_ACTIVE
    scope: RUN_TIME
    value: "database"
  - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
    scope: RUN_TIME
    value: "com.mysql.cj.jdbc.Driver"
  - key: SPRING_DATASOURCE_URL
    scope: RUN_TIME
    value: "jdbc:mysql://db-mysql-nyc3-14508-do-user-26340291-0.k.db.ondigitalocean.com:25060/celebrity_graph?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true"
  - key: DB_HOST
    scope: RUN_TIME
    value: "db-mysql-nyc3-14508-do-user-26340291-0.k.db.ondigitalocean.com"
  - key: DB_PORT
    scope: RUN_TIME
    value: "25060"
  - key: DB_NAME
    scope: RUN_TIME
    value: "celebrity_graph"
  - key: DB_USERNAME
    scope: RUN_TIME
    value: "doadmin"
  - key: DB_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: BFS_MAX_VISITED
    scope: RUN_TIME
    value: "3000000"
  - key: BFS_MAX_QUEUE
    scope: RUN_TIME
    value: "1000000"
  - key: SKIP_DATA_LOADING
    scope: RUN_TIME
    value: "false"
  - key: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_BOOT_AUTOCONFIGURE
    scope: RUN_TIME
    value: "DEBUG"
